version: "3.9"
services:
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  vdb:
    container_name: vdb
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  firebase:
    image: node:18
    container_name: firebase-emulator
    working_dir: /workspace
    volumes:
      - ./firebase:/workspace
    ports:
      - "4000:4000"
      - "9099:9099"
    command: >
      sh -c "
      npm install -g firebase-tools &&
      firebase emulators:start --only auth --project nextjs-nestjs-practice"

volumes:
  pgdata:
  qdrant_data:
